### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by youhost-joseph** [keeweb/keeweb-connect#7]
Hello, thank you very much for this software.
Unfortunately I am unable to connect:
```
Connection state: Error
Cannot connect to KeeWeb, please check if KeeWeb is open and browser integration is enabled in settings.
```
- osx 10.12
- KeeWeb v1.18.3 (337ef44, 2021-05-09)
- firefox 88.0.1 (64-bit)
- firefox KeeWeb Connect enabled in settings/browser

**Comment by antelle** [comment]
Hi! What do you see if you inspect the so-called background page of the extension?

**Comment by youhost-joseph** [comment]
Hi, here is what I see in the debug

`sendRemoveListener on closed conduit keeweb-connect@keeweb.info.824633724614 ConduitsChild.jsm:108
    _send resource://gre/modules/ConduitsChild.jsm:108
    _send self-hosted:1277
    removeListener resource://gre/modules/ExtensionChild.jsm:663
    removeListener resource://gre/modules/ExtensionChild.jsm:886
    onChanged chrome://extensions/content/child/ext-storage.js:332
    removeListener resource://gre/modules/ExtensionCommon.jsm:2523
    revoke resource://gre/modules/ExtensionCommon.jsm:2545
    close resource://gre/modules/ExtensionCommon.jsm:2550
    unload resource://gre/modules/ExtensionCommon.jsm:912
    unload resource://gre/modules/ExtensionPageChild.jsm:261
    unload resource://gre/modules/ExtensionPageChild.jsm:298
    destroyExtensionContext resource://gre/modules/ExtensionPageChild.jsm:482
    observe resource://gre/modules/ExtensionPageChild.jsm:395
Config changed background.js:631:21
Connecting to KeeWeb background.js:600:17
-> KW 
Object { action: "change-public-keys", extensionName: "KeeWeb Connect", version: "0.3.4", publicKey: "TBUKeiqt8Vf1m+Y/zbV5tz5NpnimC/89y67RRYWHo3Y=", nonce: "W+BM9zpAjbhJq9eY1nf936d4uFXWSpR7", clientID: "vkAtZ2onAiUXZjk9QUTaUY6Z0KdXQiPe" }
background.js:692:17
KeeWeb host disconnected undefined background.js:1459:21
KeeWeb disconnected background.js:644:21
Connect error Error: Cannot connect to KeeWeb, please check if KeeWeb is open and browser integration is enabled in settings.
    rejectPendingRequests moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:715
    initTransport moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:655
    emit moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:160
    portDisconnected moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:1460
    connect moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:1436
background.js:621:21
    connect moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:621
    processMessage moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:966
    startInternalIpc moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:945
`

**Comment by youhost-joseph** [comment]
sendRemoveListener on closed conduit keeweb-connect@keeweb.info.824633724614 ConduitsChild.jsm:108
    _send resource://gre/modules/ConduitsChild.jsm:108
    _send self-hosted:1277
    removeListener resource://gre/modules/ExtensionChild.jsm:663
    removeListener resource://gre/modules/ExtensionChild.jsm:886
    onChanged chrome://extensions/content/child/ext-storage.js:332
    removeListener resource://gre/modules/ExtensionCommon.jsm:2523
    revoke resource://gre/modules/ExtensionCommon.jsm:2545
    close resource://gre/modules/ExtensionCommon.jsm:2550
    unload resource://gre/modules/ExtensionCommon.jsm:912
    unload resource://gre/modules/ExtensionPageChild.jsm:261
    unload resource://gre/modules/ExtensionPageChild.jsm:298
    destroyExtensionContext resource://gre/modules/ExtensionPageChild.jsm:482
    observe resource://gre/modules/ExtensionPageChild.jsm:395
Config changed background.js:631:21
Connecting to KeeWeb background.js:600:17
-> KW 
Object { action: "change-public-keys", extensionName: "KeeWeb Connect", version: "0.3.4", publicKey: "TBUKeiqt8Vf1m+Y/zbV5tz5NpnimC/89y67RRYWHo3Y=", nonce: "W+BM9zpAjbhJq9eY1nf936d4uFXWSpR7", clientID: "vkAtZ2onAiUXZjk9QUTaUY6Z0KdXQiPe" }
background.js:692:17
KeeWeb host disconnected undefined background.js:1459:21
KeeWeb disconnected background.js:644:21
Connect error Error: Cannot connect to KeeWeb, please check if KeeWeb is open and browser integration is enabled in settings.
    rejectPendingRequests moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:715
    initTransport moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:655
    emit moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:160
    portDisconnected moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:1460
    connect moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:1436
background.js:621:21
    connect moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:621
    processMessage moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:966
    startInternalIpc moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:945

**Comment by youhost-joseph** [comment]
would you like me to send a screenshot for better reading?

**Comment by antelle** [comment]
That's enough, for some reason KeeWeb disconnects from the extension. Do you see anything in KeeWeb devtools, if you bring it up (devtools can be opened either in settings, or using <kbd>⌥</kbd><kbd>⌘</kbd><kbd>I</kbd>)?

**Comment by youhost-joseph** [comment]
Sorry for the late reply.
At some point there was this error in KeeWeb:
`GET file:///Applications/KeeWeb.app/Contents/Resources/app.asar/manifest.json net::ERR_FILE_NOT_FOUND`
But I was unable to reproduce it again.

**Comment by antelle** [comment]
That's fine, this error always happens and it's not an issue.
Let's check if the native messaging host is working. Could you please open DevTools Console in KeeWeb and then do this:
```
/Applications/KeeWeb.app/Contents/MacOS/util/keeweb-native-messaging-host keeweb-connect@keeweb.info
```

Expected result:
![image](https://user-images.githubusercontent.com/633557/117580242-6736fe00-b0f7-11eb-83ea-795b15580c01.png)

**Comment by youhost-joseph** [comment]
I've try to connect to my KeeWeb via nextcloud with web-only but got the same error:
```
Config changed 2 background.js:631:21
Connecting to KeeWeb background.js:600:17
Connect error Error: Cannot connect to KeeWeb, refreshing a tab with KeeWeb may help. Inspect the extension background page to get more details.
    connect moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:1287
    connect moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:612
    processMessage moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:966
    startInternalIpc moz-extension://9820c294-346a-7547-b232-f49f507f2fce/js/background.js:945
```
So I reset to the default URL (https://app.keeweb.info) and open the db and all works fine.
Then I created a new db in KeeWeb just to be sure that there was not anything weird in my wallet, but I got the same error.

Let me know if I can help further to debug this.

**Comment by antelle** [comment]
Wait, are you trying to connect to a native app or a browser tab in KeeWeb?

If it's the native app, please do what I asked above.

If it's a web mode, I assume it won't work with nextcloud-keeweb. This is designed to work exactly with KeeWeb (app.keeweb.info) or your self-hosted version.

**Comment by youhost-joseph** [comment]
Hi Antelle, I confirm I want to connect with the native app, the browser experiment was just to further debug.
So I did sent the cmd via console in KeeWeeb but got this:
`Uncaught SyntaxError: Invalid regular expression flags`

While in apple terminal I got this:
```
dyld: Symbol not found: __ZdlPvSt11align_val_t
  Referenced from: /Applications/KeeWeb.app/Contents/MacOS/util/./keeweb-native-messaging-host
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/KeeWeb.app/Contents/MacOS/util/./keeweb-native-messaging-host
Abort trap: 6
```

**Comment by antelle** [comment]
I see, thanks for testing it! I think it's because of old macOS. I made a binary that should work on macOS 10.11+, could you please give it a test?
[keeweb-native-messaging-host.zip](https://github.com/keeweb/keeweb-connect/files/6448303/keeweb-native-messaging-host.zip)

**Comment by youhost-joseph** [comment]
Hello Antelle, yes this fix works!
`Connection state: Connected`
